Feature: Design Forms using Data Dictionary & Online Designer

  As a REDCap end user
  I want to see that Design Forms using Data Dictionary & Online Designer are functioning as expected

  Scenario: Describe scenario here

Scenario: Create a new project with title "TestingProject", purpose "Practice / Just for fun" and Project creation opion "Empty project (blank state)"
    Given I am an "admin" user who logs into REDCap
    And I click on the link labeled "New Project"
    And I enter "TestingProject" into the field identified by "[name=app_title]"
    And I select "Practice / Just for fun" from the dropdown identified by "select[name=purpose]"
    When I click on the button labeled "Create Project"
    Then I should see "Your new REDCap project has been created and is ready to be accessed."

Scenario: I can create a new form labeled "FormTesting"
  Given I click on the link labeled "Designer"
  And I click on the button labeled " Create"
  And I click on the button labeled "Add instrument here"
  And I enter "FormTesting" into the field identified by "input[type='text']" labeled "New instrument name:"
  And I click on the input button labeled "Create"
  Then I should see " The new instrument was successfully created. The page will be reloaded to reflect this change."
  Then I click on the button labeled "Close"

Scenario: I can add a field to the form "FormTesting" of type "Text Box (Short Text, Number, Date/Time, ...)"
  Given I click on the table cell containing a link labeled "FormTesting"
  And I click on the input button labeled "Add Field"
  And I select the value "Text Box (Short Text, Number, Date/Time, ...)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "TextBox Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "textboxname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I select the value "Date (D-M-Y)" from the dropdown identified by "select[name=val_type]" labeled "Validation?"
  And I mark the field required
  And I click on the element identified by "input#field_phi1"
  And I enter "Small text description" into the field labeled "Field Note"
  And I select the value "Left / Vertical (LV)" from the dropdown identified by "select[name=custom_alignment]" labeled "Custom Alignment"
  And I click on the button labeled "Save"
  Then I should see "TextBox Name"

Scenario: I can add a field to the form "FormTesting" of type "Notes Box (Paragraph Text)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Notes Box (Paragraph Text)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Notes Box Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "textareaname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Notes Box Name"

Scenario: I can add a field to the form "FormTesting" of type "Calculated Field"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Calculated Field" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Calculated Field Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "calcname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Calculated Field Name"

Scenario: I can add a field to the form "FormTesting" of type "Multiple Choice - Drop-down List (Single Answer)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Multiple Choice - Drop-down List (Single Answer)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Select Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "selectname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I enter the value "0,No\n1,Yes" into the field identified by "textarea[name=element_enum]" labeled "Choices (one choice per line)"
  And I click on the button labeled "Save"
  Then I should see "Select Name"

Scenario: I can add a field to the form "FormTesting" of type "Multiple Choice - Radio Buttons (Single Answer)adio"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Multiple Choice - Radio Buttons (Single Answer)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Radio Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "radioname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I enter the value "0,No\n1,Yes" into the field identified by "textarea[name=element_enum]" labeled "Choices (one choice per line)"
  And I click on the button labeled "Save"
  Then I should see "Radio Name"

Scenario: I can add a field to the form "FormTesting" of type "Checkboxes (Multiple Answers)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Checkboxes (Multiple Answers)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Checkbox Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "checkboxname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I enter the value "0,No\n1,Yes" into the field identified by "textarea[name=element_enum]" labeled "Choices (one choice per line)"
  And I click on the button labeled "Save"
  Then I should see "Checkbox Name"

Scenario: I can add a field to the form "FormTesting" of type "Yes - No"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Yes - No" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Yes-No Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "yesnoname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Yes-No Name"

Scenario: I can add a field to the form "FormTesting" of type "True - False"
  Given I click on the first input button labeled "Add Field"
  And I select the value "True - False" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "True-False Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "truefalsename" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "True-False Name"

Scenario: I can add a field to the form "FormTesting" of type "Signature (draw signature with mouse or finger)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Signature (draw signature with mouse or finger)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Signature Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "signaturename" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Signature Name"

  Scenario: I can add a field to the form "FormTesting" of type "File Upload (for users to upload files)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "File Upload (for users to upload files)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "File Upload Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "fileuploadname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "File Upload Name"

Scenario: I can add a new section to the form called "New section"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Begin New Section (with optional text)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "New Section" into the field identified by "[name=field_label]" labeled "Field Label"
  And I click on the button labeled "Save"
  Then I should see "New Section"

  Scenario: I can add a field to the form "FormTesting" of type "Slider / Visual Analog Scale"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Slider / Visual Analog Scale" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Slider Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "slidername" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Slider Name"

  Scenario: I can add a field to the form "Descriptive Text (with optional Image/Video/Audio/File Attachment)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Descriptive Text (with optional Image/Video/Audio/File Attachment)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Descriptive Text Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "descriptivetextname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Descriptive Text Name"

  Scenario: I can add a field to the form "Dynamic Query (SQL)"
  Given I click on the first input button labeled "Add Field"
  And I select the value "Dynamic Query (SQL)" from the dropdown identified by "select[name=field_type]" labeled "Field Type:"
  And I enter the value "Dynamic Query Name" into the field identified by "[name=field_label]" labeled "Field Label"
  And I enter the value "dynamicqueryname" into the field identified by "input[name=field_name]" labeled "Variable Name"
  And I click on the button labeled "Save"
  Then I should see "Dynamic Query Name"
